# Generated by Django 5.2.10 on 2026-02-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clinic", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="followup",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
